// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPESSC.Data;

#nullable disable

namespace UPESSC.Migrations
{
    [DbContext(typeof(UPESSCDbContext))]
    [Migration("20250913111857_Users")]
    partial class Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UPESSC.Models.Candidate", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CID"));

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("DOB")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FatherOrHusbandName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("InterviewBoard")
                        .HasColumnType("longtext");

                    b.Property<string>("InterviewDate")
                        .HasColumnType("longtext");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubCategory")
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("longtext");

                    b.HasKey("CID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("UPESSC.Models.CandidateEducationalQualification", b =>
                {
                    b.Property<int>("CEQID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CEQID"));

                    b.Property<string>("BoardOrUniversity")
                        .HasColumnType("longtext");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<string>("CertificatePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Examination")
                        .HasColumnType("longtext");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext");

                    b.Property<string>("MarkSheetpath")
                        .HasColumnType("longtext");

                    b.Property<string>("MarksObtained")
                        .HasColumnType("longtext");

                    b.Property<string>("Percentage")
                        .HasColumnType("longtext");

                    b.Property<string>("RollNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalMarks")
                        .HasColumnType("longtext");

                    b.Property<string>("YearOfPassing")
                        .HasColumnType("longtext");

                    b.HasKey("CEQID");

                    b.ToTable("CandidateEducationalQualifications");
                });

            modelBuilder.Entity("UPESSC.Models.Institute", b =>
                {
                    b.Property<int>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IID"));

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("longtext");

                    b.Property<bool?>("isFemaleInstitute")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IID");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("UPESSC.Models.Subject", b =>
                {
                    b.Property<int>("SID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SID"));

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("UPESSC.Models.User", b =>
                {
                    b.Property<int>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UID"));

                    b.Property<string>("Admin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
