// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPESSC.Data;

#nullable disable

namespace UPESSC.Migrations
{
    [DbContext(typeof(UPESSCDbContext))]
    [Migration("20250914041525_CandidateInstitutePreference")]
    partial class CandidateInstitutePreference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UPESSC.Models.Candidate", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CID"));

                    b.Property<string>("Aadhaar_No")
                        .HasColumnType("longtext");

                    b.Property<string>("Address_Line1")
                        .HasColumnType("longtext");

                    b.Property<string>("Address_Line2")
                        .HasColumnType("longtext");

                    b.Property<string>("Address_Line3")
                        .HasColumnType("longtext");

                    b.Property<string>("Address_Line4")
                        .HasColumnType("longtext");

                    b.Property<string>("Address_Line5")
                        .HasColumnType("longtext");

                    b.Property<string>("Category_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Created_Date")
                        .HasColumnType("longtext");

                    b.Property<string>("DFF")
                        .HasColumnType("longtext");

                    b.Property<string>("Date_of_Birth")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<long>("Enrollment_No")
                        .HasColumnType("bigint");

                    b.Property<string>("Father_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Husband_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("JRF_Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Marital_Status")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNo")
                        .HasColumnType("longtext");

                    b.Property<string>("Mother_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NET_Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PG_Before_91")
                        .HasColumnType("longtext");

                    b.Property<string>("PH")
                        .HasColumnType("longtext");

                    b.Property<string>("Payment_Date")
                        .HasColumnType("longtext");

                    b.Property<string>("Payment_ID")
                        .HasColumnType("longtext");

                    b.Property<string>("Payment_Mode")
                        .HasColumnType("longtext");

                    b.Property<string>("Payment_Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Permanent_Address_Line1")
                        .HasColumnType("longtext");

                    b.Property<string>("Permanent_Address_Line2")
                        .HasColumnType("longtext");

                    b.Property<string>("Permanent_Address_Line3")
                        .HasColumnType("longtext");

                    b.Property<string>("Permanent_Address_Line4")
                        .HasColumnType("longtext");

                    b.Property<string>("Permanent_Address_Line5")
                        .HasColumnType("longtext");

                    b.Property<string>("Permanent_District")
                        .HasColumnType("longtext");

                    b.Property<string>("Permanent_Postal_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Permanent_State")
                        .HasColumnType("longtext");

                    b.Property<string>("Phd_Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Photo_File")
                        .HasColumnType("longtext");

                    b.Property<string>("Postal_Code")
                        .HasColumnType("longtext");

                    b.Property<string>("RollNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("SLET_Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Sign_File")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("Sub_Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Subject_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("UP_Resident")
                        .HasColumnType("longtext");

                    b.Property<string>("is_JRF")
                        .HasColumnType("longtext");

                    b.Property<string>("is_NET")
                        .HasColumnType("longtext");

                    b.Property<string>("is_Phd")
                        .HasColumnType("longtext");

                    b.Property<string>("is_SLET_SET")
                        .HasColumnType("longtext");

                    b.HasKey("CID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("UPESSC.Models.CandidateEducationalQualification", b =>
                {
                    b.Property<int>("CEQID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CEQID"));

                    b.Property<string>("BoardOrUniversity")
                        .HasColumnType("longtext");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<string>("CertificatePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Examination")
                        .HasColumnType("longtext");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext");

                    b.Property<string>("MarkSheetpath")
                        .HasColumnType("longtext");

                    b.Property<string>("MarksObtained")
                        .HasColumnType("longtext");

                    b.Property<string>("Percentage")
                        .HasColumnType("longtext");

                    b.Property<string>("RollNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalMarks")
                        .HasColumnType("longtext");

                    b.Property<string>("YearOfPassing")
                        .HasColumnType("longtext");

                    b.HasKey("CEQID");

                    b.ToTable("CandidateEducationalQualifications");
                });

            modelBuilder.Entity("UPESSC.Models.CandidateInstitutePreference", b =>
                {
                    b.Property<int>("CIPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CIPID"));

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("IID")
                        .HasColumnType("int");

                    b.Property<int>("PreferenceOrder")
                        .HasColumnType("int");

                    b.HasKey("CIPID");

                    b.ToTable("CandidateInstitutePreferences");
                });

            modelBuilder.Entity("UPESSC.Models.ExaminationMasters", b =>
                {
                    b.Property<int>("ExaminationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExaminationID"));

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ExaminationID");

                    b.ToTable("ExaminationMasters");
                });

            modelBuilder.Entity("UPESSC.Models.Institute", b =>
                {
                    b.Property<int>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IID"));

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("longtext");

                    b.Property<bool?>("isFemaleInstitute")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IID");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("UPESSC.Models.Subject", b =>
                {
                    b.Property<int>("SID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SID"));

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectNameEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("UPESSC.Models.User", b =>
                {
                    b.Property<int>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UID"));

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
